### PR TITLE
Upgrade to Jetty 9.4.x

### PR DESCRIPTION
**Pull request by jkoelker**
* Upgrades to Jetty 9.4.x by hoping through 7.x and 8.x changes first
* Removes backported `ExecutorThreadPool` and uses upstream
* Sets `web.xml` directly instead of instrumenting `SecurityHandler` extraction

DC/OS Tests PR: https://github.com/dcos/dcos/pull/7490
DC/OS Ent Tests PR: https://github.com/mesosphere/dcos-enterprise/pull/8068

### CODE REVIEW

**Comment by jongiddy** [comment]
Unfortunately there's no CI for this repo. I test using:
```
docker run --rm -u $(id -u) -v "$PWD":/home/gradle/project -w /home/gradle/project gradle:5.6.4-jdk8 gradle --info build
```
When I run that command on this branch I get:
```
Compiling with JDK Java compiler API.
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:25: error: cannot find symbol
import org.eclipse.jetty.security.SslSelectChannelConnector;
                                 ^
  symbol:   class SslSelectChannelConnector
  location: package org.eclipse.jetty.security
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:26: error: package org.eclipse.jetty.servlet does not exist
import org.eclipse.jetty.servlet.ServletContextHandler;
                                ^
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:27: error: package org.eclipse.jetty.servlet does not exist
import org.eclipse.jetty.servlet.ServletHolder;
                                ^
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:58: error: cannot find symbol
        SslSelectChannelConnector connector = new SslSelectChannelConnector();
        ^
  symbol:   class SslSelectChannelConnector
  location: class JettyServer
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:58: error: cannot find symbol
        SslSelectChannelConnector connector = new SslSelectChannelConnector();
                                                  ^
  symbol:   class SslSelectChannelConnector
  location: class JettyServer
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:82: error: cannot find symbol
        ServletContextHandler context = new ServletContextHandler(server, "/", Context.SESSIONS);
        ^
  symbol:   class ServletContextHandler
  location: class JettyServer
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:82: error: cannot find symbol
        ServletContextHandler context = new ServletContextHandler(server, "/", Context.SESSIONS);
                                            ^
  symbol:   class ServletContextHandler
  location: class JettyServer
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:82: error: cannot find symbol
        ServletContextHandler context = new ServletContextHandler(server, "/", Context.SESSIONS);
                                                                               ^
  symbol:   variable Context
  location: class JettyServer
/home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/automanage/JettyServer.java:83: error: cannot find symbol
        context.addServlet(new ServletHolder(container), "/*");
                               ^
  symbol:   class ServletHolder
  location: class JettyServer
Note: /home/gradle/project/exhibitor-core/src/test/java/com/netflix/exhibitor/core/s3/TestRefCountedClient.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':exhibitor-core:compileTestJava'.
```

I see you have made some similar changes to other places using `SslSelectChannelConnector` so hopefully this identifies where a change has been missed, and you have a reasonable idea of how to fix it. Or maybe my command above should be changed to handle the new code?

It would be good to have this command, or a similar command, working before we merge.  Ideally this would go into a CI job as well.

**Comment by jkoelker** [comment]
I think the issue is caused by not using the gradle wrapper so the paths aren't setup right. I had been testing it in just the openjdk8 container with :

```
docker run -ti --rm -v "$(pwd)":"$(pwd)" -w "$(pwd)" openjdk:8                                                                                                                        
root@f4e7b63d5025:/Users/jkoelker/dcos/exhibitor# ./gradlew install && ./gradlew -b exhibitor-standalone/src/main/resources/buildscripts/standalone/gradle/build.gradle shadowJar
```

I snagged those gradle commands from the `build` script in dcos.

**Comment by jkoelker** [comment]
ah, those are the tests, yea I didn't update any of the tests.

**Comment by jkoelker** [comment]
@jongiddy I cherry-picked over the commits from #18 and got the tests to pass.

**Comment by jongiddy** [comment]
This is great! I'm very happy with this. There is just one small thing that would be useful. It seems like we have reasons for the `with` clauses in the new `gradle.yml`. Can you please add comments to these to explain why they are needed, and hence, what might be the effect if we choose to change them at a later date?

**Comment by jkoelker** [comment]
:+1: I updated the last two commits to add in comments.

**Review by jongiddy — APPROVED** [review]
Brilliant work! Thanks very much for putting the effort into this!

**Pull request merged**
